spring:
  application:
    name: cp
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cp
    username: root
    password: root
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.zcw.cpbackend.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn


# Sa-Token配置
sa-token:
  token-name: satoken
  timeout: 86400 # 7days
  active-timeout: -1
  is-concurrent: true # concurrent login
  is-share: true
#  token-template: org.springframework.data.redis.core.RedisTemplate # Token的持久层框架，Redis
  log-display: true


